name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Java
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    # Setup Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    # Setup Dart
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    # Cache Gradle dependencies
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    # Grant execute permissions
    - name: Grant execute permissions
      run: |
        chmod +x gradlew
        chmod +x generate_all.sh
        
    # Run build_runner
    - name: Run build_runner
      run: dart run build_runner build --delete-conflicting-outputs
      
    # Run generate_all.sh
    - name: Run generate_all script
      run: sh generate_all.sh
      
    # Build APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    # Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk