name: Build and Release APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Java
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    # Setup Dart
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    # Get Flutter dependencies
    - name: Get dependencies
      run: flutter pub get
    
    # Grant execute permissions
    - name: Grant execute permissions
      run: chmod +x generate_i18n.sh
      
    - name: Install flutter_localizations
      run: flutter pub add flutter_localization

    # Run build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
  
    - name: Run generate_all script
      run: sh generate_i18n.sh

    # Build APK (เปลี่ยนจาก debug เป็น release)
    - name: Build APK
      run: flutter build apk --release
      
    # Create Release and Upload APK
    - name: Create Release and Upload APK
      if: github.event_name == 'push'  # รันเฉพาะเมื่อ push ไม่รันใน pull request
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}