name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Setup Java
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    # Setup Dart (included with Flutter, but explicit setup for clarity)
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    # Get Flutter dependencies
    - name: Get dependencies
      run: flutter pub get
    
    # Grant execute permissions
    - name: Grant execute permissions
      run: chmod +x generate_i18n.sh
      
    - name: Install flutter_localizations
      run: flutter pub add flutter_localization

    # Run build_runner
    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
  
    - name: Run generate_all script
      run: sh generate_i18n.sh

    - name: Run generate_all script
      run: ls -a
    # # Build APK
    # - name: Build APK
    #   run: flutter build apk --debug
      
    # # Upload APK
    # - name: Upload APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-debug.apk
    #     path: build/app/outputs/flutter-apk/app-debug.apk